#!/usr/bin/env php
<?php

require 'vendor/autoload.php';
require 'regex.class.php';

CONST BASE_URL = 'https://www.reddit.com/r/';
$options = getopt('r:l:', ['limit:']);
$limit = false;
$url = null;

if(empty($options['r']) || !regex::subreddit($options['r'])) {
	echo "Invalid subreddit name\n";
	exit();
}
$url = BASE_URL.$options['r'];

if (!empty($options['limit'])) {
	$limit = is_int($options['limit']) ? $options['limit'] : null;
}

if (!empty($options['l'] && !$limit)) {
	$limit = is_int($options['l']) ? $options['l'] : null;
}

$curl = new GuzzleHttp\Client();
$res = $curl->request('GET', $url, [
	'headers' => [
		'User-Agent' => 'Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3343.3 Safari/537.36'
	]
]);
echo $res->getBody();

?>
