#!/usr/bin/env php
<?php

require 'vendor/autoload.php';
require 'object/regex.class.php';
require 'object/UserAgent.class.php';
require 'object/Reddit.class.php';

require 'conf/const.php';
require 'conf/curl.php';

$hello_cmd = new Commando\Command();
$hello_cmd->option()
	->referToAs('subreddit')
	->require()
	->must(function ($subreddit) {
		return regex::subreddit($subreddit);
	})
	->describedAs('A subreddit\'s name');
	
$hello_cmd->option('l')
    ->aka('limit')
    ->describedAs('The number max of picture to download.')
    ->must(function($limit) {
		$limit = (int) $limit;
        return is_int($limit) && $limit > 0;
	})
	->map(function ($limit) {
		return (int) $limit;
	});

$limit = $hello_cmd['limit'] ?? null;
$url = BASE_URL . $hello_cmd[0];

$RedditDl->getImage($url, $hello_cmd[0], $limit);

?>
